package io.nikitoo0os.scheduling;

public enum ScheduleEventType {
    SCHEDULE_CREATED,
    SCHEDULE_ACTIVATED,
    SCHEDULE_COMPLETED,
    SCHEDULE_FAILED,
    SCHEDULE_CANCELLED,
    EXECUTION_EXPECTED,
    EXECUTION_STARTED,
    EXECUTION_COMPLETED,
    EXECUTION_FAILED,
    EXECUTION_CANCELLED
}
