package io.nikitoo0os.event;

public enum GhostWorkEventType {
    OPERATION_COMPLETED,
    OPERATION_FAILED,
    OPERATION_TIMED_OUT,
    OPERATION_ABORTED,
    OPERATION_CANCELLED,
    OPERATION_CANCELLATION_REQUESTED,
    TASK_CANCELLATION_REQUESTED,
    TASK_CANCELLATION_ACCEPTED,
    TASK_INTERRUPT_REQUESTED,
    TASK_CANCELLATION_OBSERVED,
    TASK_CANCELLATION_COMPLETED,
    TASK_CANCELLATION_GRACE_PERIOD_EXCEEDED,
    CANCELLATION_CALLBACK_FAILED,
    TASK_SUBMITTED,
    TASK_STARTED,
    TASK_COMPLETED,
    TASK_FAILED,
    TASK_REJECTED,
    TASK_CANCELLED
}
